### ISSUE TITLE
Rule management will change with PowerTrack 2.0

### ISSUE THREAD

**Issue by j-bennet** [abh1nav/gnippy#19]
With PowerTrack 2.0 migration coming up (deadline is December 1, 2016), the following will not be valid anymore:

https://github.com/abh1nav/gnippy/blob/9765bbec50e454240031b5dd3f9a987a40f270b3/gnippy/rules.py#L17-L24

Instead of:

`https://api.gnip.com:443/accounts/<account-name>/publishers/twitter/streams/track/<stream-label>/rules.json`

rules will have to be posted to:

`https://gnip-api.twitter.com/rules/powertrack/accounts/<account-name>/publishers/twitter/<stream-label>.json`.

It would be better if gnippy accepted `rules_url` as part of the config.

In addition, [rule deletion](https://github.com/abh1nav/gnippy/blob/9765bbec50e454240031b5dd3f9a987a40f270b3/gnippy/rules.py#L102-L123) will now be done with a POST request and `&_method=delete` parameter (from [here](http://support.gnip.com/articles/migrating-gnip-code.html)).

**Comment by abh1nav** [comment]
@j-bennet I don't have access to PowerTrack anymore since we stopped using it at work. I can make you a contributor to this repo if you'd like to fix it?

**Comment by j-bennet** [comment]
Yes please.

**Comment by abh1nav** [comment]
@j-bennet done. You can ping me here when you need it deployed to PyPI.

**Comment by j-bennet** [comment]
@abh1nav Thanks, will do.

**Comment by j-bennet** [comment]
Fixed via https://github.com/abh1nav/gnippy/pull/20.

**Comment by abh1nav** [comment]
@j-bennet PyPI updated to [v0.6.0](https://pypi.python.org/pypi/gnippy/0.6.0)
Thanks for the update! 😊

Tagging PR #20

**Comment by j-bennet** [comment]
Thank you!
