### ISSUE TITLE
New release is needed

### ISSUE THREAD

**Issue by j-bennet** [abh1nav/gnippy#31]
@abh1nav We're using `gnippy` in parse.ly. We need a release after this PR was merged, otherwise our dependencies end up in a bad state:

https://github.com/abh1nav/gnippy/pull/29

Any chance you could do a release, or make me or @dan-blanchard  a `gnippy` maintainer on pypi?

**Comment by abh1nav** [comment]
@j-bennet Happy to make that happen. What's your pypi username?

**Comment by j-bennet** [comment]
My `pypi` username is `icherniavska`. Thanks a lot!

**Comment by abh1nav** [comment]
@j-bennet done!

**Comment by j-bennet** [comment]
Released 0.7.0!
