### ISSUE TITLE
Data loss when stop requested

### ISSUE THREAD

**Issue by everilae** [abh1nav/gnippy#5]
When `Worker` is requested to stop it will do so at once when possible, which is when `r.iter_lines` wakes up and returns data. Depending on the stream and rules this could either be just an ack with high probability, or precious JSON.

```
    for line in r.iter_lines():
        if self.stopped():
            break

        elif line:
            self.on_data(line)
```

It is a bit of an opinionated subject, but to me it seems like it should handle the possibly received data and then stop.

**Comment by abh1nav** [comment]
I think you're right. Something like this might be better:

``` python
for line in r.iter_lines():
  self.on_data(line)
  if self.stopped():
    break
```

We don't really need to differentiate between acks and JSON because that should be handled by the `on_data` function since acks are a normal part of being connected to the stream.

**Comment by abh1nav** [comment]
Actually, on second thought, since the current worker is filtering out the acks, changing it would break compatibility.

**Comment by everilae** [comment]
Just what I had in mind, thanks :)
