### ISSUE TITLE
Bad credentials don't throw an error

### ISSUE THREAD

**Issue by faaez** [abh1nav/gnippy#6]
It would be great if the client could throw an error if the credentials are wrong. Right now looks like the client is just waiting for data to come back. Happy to work on this if you like. 

Thanks for your great work on this!

**Comment by abh1nav** [comment]
@faaez thanks! I've pushed a fix but I don't have GNIP creds at the moment - would you be able to test it out and let me know if it works?

**Comment by abh1nav** [comment]
@faaez bump

**Comment by faaez** [comment]
Just tested it - it works. Thank you @abh1nav !
